-- Run this SQL in your Supabase SQL Editor to create the products table and insert initial data.

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert the initial Aurelia product catalog
INSERT INTO public.products (name, price, image, description)
VALUES 
  ('Obsidian Blazer', 1250.00, '/assets/obsidian_blazer.png', 'Meticulously crafted to represent the pinnacle of modern luxury.'),
  ('Champagne Silk Dress', 890.00, '/assets/champagne_silk_dress.png', 'A testament to uncompromising quality and timeless minimalist design.'),
  ('Gold Cuff Bracelet', 450.00, '/assets/gold_cuff_bracelet.png', 'Ethically sourced materials with hand-finished detailing.'),
  ('Leather Tote Bag', 1800.00, '/assets/leather_tote_bag.png', 'Designed for the digital-first connoisseur, bridging the gap between aesthetics and utility.');
